name: Keep Alive Ping

on:
  schedule:
    # Runs every 10 minutes
    - cron: "*/10 * * * *"  # Adjusted to match the 10-minute interval in ping.js
  workflow_dispatch:  # Allows manual triggers

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        npm install axios
    - name: Run Ping Script
      run: |
        node ping.js
